version: '4.20'

services:
  app:
    build:
      context: .
      dockerfile: ./dockerfile
    command: flask run
    ports:
      - '8080:5000'
    environment:
      - FLASK_ENV=production  
    volumes:
      - .:/app:ro
      - ./logs:/logs  # Optional log dir
    depends_on:
      - suricata
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 5s
      retries: 3

  grafana:
    image: grafana/grafana:9.2.15
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - '3000:3000'
    depends_on:
      - suricata
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3

  suricata:
    image: jasonish/suricata:latest
    ports:
      - '3001:3001'  # For GUI
    volumes:
      - ./suricata:/var/log/suricata  # Storage for logs
      - /etc/suricata:/etc/suricata  # Suricata config
    command: suricata -c /etc/suricata/suricata.yaml -i eth0
    cap_add:
      - NET_ADMIN
      - NET_RAW
    healthcheck:
      test: ["CMD", "pidof", "suricata"]
      interval: 30s
      timeout: 5s
      retries: 3
