FROM debian:latest
      #  or  python:3.11-slim for save on space at least
      # i would rather use kinda debian or centos images, i will get a way more possibilities, comparing with just python env.
      # Moreover, no other option except deb/cent/alt/alpine etc in prod. 

ENV PYTHONUNBUFFERED=1 \
    FLASK_APP=app.py \
    FLASK_RUN_HOST=0.0.0.0 \
    FLASK_RUN_PORT=5000

WORKDIR /var/www/app

RUN apt-get update && apt-get install -y --no-install-recommends \ 
    python3 python3-dev python3-pip python3-venv libssl-dev python3-setuptools \
    build-essential \
    libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/

COPY requirements.txt .
      # be 100% sure that reqs contain gunicorn, flask, gevent, eventlet
RUN pip install --no-cache-dir --upgrade pip setuptools \
    && pip install --no-cache-dir wheel && pip install --no-cache-dir -r requirements.txt

COPY . .

RUN useradd -m flaskuser
USER flaskuser

EXPOSE 5000

CMD ["flask", "run"]
